reporting: "off"
startuppopupversion: 1
gui:
    # stuff relating to the UI
    scrollHeight: 2 # how many lines you scroll by
    scrollPastBottom: true # enable scrolling past the bottom
    sidePanelWidth: 0.3333 # number from 0 to 1
    theme:
      lightTheme: false # For terminals with a light background
      activeBorderColor:
        - blue
        - bold
      inactiveBorderColor:
        - white
      optionsTextColor:
        - blue
      selectedLineBgColor:
        - white
      selectedRangeBgColor:
        - blue
    commitLength:
      show: true
    mouseEvents: true
    skipUnstageLineWarning: false
    skipStashWarning: true
