name: flake-update

on:
  schedule:
    # Runs at 04:00 UTC daily
    - cron: "0 4 * * *"
  workflow_dispatch:

permissions:
  contents: write        # push branches
  pull-requests: write   # open PRs & enable auto-merge

concurrency:
  group: flake-lock-updater
  cancel-in-progress: false

jobs:
  update-flake-lock:
    runs-on: self-hosted
    steps:
      - name: Checkout (full history for clean diffs)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update flake.lock
        run: |
          set -euo pipefail
          nix --version

          # update flake inputs, create a commit with more details in the message
          nix flake update --commit-lock-file

          # check if commit was made, if nothing changed, bail out early
          if git diff --quiet '@{upstream}..' -- flake.lock; then
            echo "No flake.lock changes." | tee -a "$GITHUB_STEP_SUMMARY"
            echo "have_changes=" >> "$GITHUB_OUTPUT"
            exit
          fi

          echo "have_changes=true" >> "$GITHUB_OUTPUT"
          {
            echo "commit_message<<EOF"
            git log -n 1 --format='%b'
            echo "EOF"
          } >> "$GITHUB_OUTPUT"
          {
            echo '```'
            git log -n 1 --format='%b'
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"
        id: update

      - name: Create pull request
        if: steps.update.outputs.have_changes
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          commit-message: "flake.lock: Update"
          title: "flake.lock: Update"
          body: |
            Automated `nix flake update`.
            Generated by ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            Updated inputs:
            ```
            ${{ steps.update.outputs.commit_message }}
            ```

          branch: flake-lock-update
          delete-branch: true

      - name: Enable auto-merge (rebase)
        if: steps.update.outputs.no_changes == 'false'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: rebase
